
import { GoogleGenAI } from "@google/genai";

// Generate professional headshot using gemini-2.5-flash-image
export const generateProfessionalHeadshot = async (
  base64Image: string,
  stylePrompt: string
): Promise<string> => {
  // Always initialize GoogleGenAI with { apiKey: process.env.API_KEY } directly before use.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
  
  // Strip the prefix "data:image/png;base64," etc. if present
  const base64Data = base64Image.split(',')[1] || base64Image;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Data,
            mimeType: 'image/png',
          },
        },
        {
          text: stylePrompt,
        },
      ],
    },
  });

  // Iterate through all parts to find the image part, as it might not be the first part.
  if (response.candidates && response.candidates.length > 0) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
  }

  throw new Error('No image was generated by the model.');
};

// Edit existing image with a user-provided prompt
export const editImageWithPrompt = async (
  base64Image: string,
  userPrompt: string
): Promise<string> => {
  // Always initialize GoogleGenAI with { apiKey: process.env.API_KEY } directly before use.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
  
  const base64Data = base64Image.split(',')[1] || base64Image;

  const prompt = `Modify the provided image according to this instruction: "${userPrompt}". 
                  Maintain the person's core features while applying the requested changes. 
                  Ensure the result remains professional and high-quality.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Data,
            mimeType: 'image/png',
          },
        },
        {
          text: prompt,
        },
      ],
    },
  });

  // Iterate through all parts to find the image part in the response.
  if (response.candidates && response.candidates.length > 0) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
  }

  throw new Error('Could not edit the image with the provided prompt.');
};
